import { Metadata } from 'next'
import '../styles.css'
import { cn } from '@/lib/utils'
import { Vazirmatn } from 'next/font/google'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'

const vazir = Vazirmatn({
  subsets: ['arabic'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-vazir',
})

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl" className={cn('h-full', vazir.className)}>
      <body className={cn('relative h-full font-vazir antialiased bg-background text-foreground')}>
        <main>
          <Providers>
            <div className="flex justify-center">{children}</div>
          </Providers>
        </main>

        <Toaster
          position="top-center"
          richColors
          toastOptions={{
            style: {
              borderColor: 'var(--primary)',
              backgroundColor: '#d9d2f7',
              color: 'black',
            },
          }}
        />
      </body>
    </html>
  )
}
